PRAGMA foreign_keys = ON;

ALTER TABLE products ADD COLUMN inventory_mode TEXT;
ALTER TABLE components ADD COLUMN stock_qty INTEGER NOT NULL DEFAULT 0;
ALTER TABLE components ADD COLUMN min_stock INTEGER NOT NULL DEFAULT 0;
ALTER TABLE components ADD COLUMN is_active INTEGER NOT NULL DEFAULT 1;
